GEMINI_MODEL: "gemini-3-flash-preview"
DEVICE_SERIAL: "emulator-5554"  # adb devices
OUTPUT_DIR: "./output"
MAX_STEPS: 25

VLLM_MODEL: "Qwen/Qwen3-VL-8B-Instruct"
VLLM_BASE_URL: "http://127.0.0.1:8000/v1"
